<?php

namespace App\Libraries;

use GuzzleHttp\Client;

/**
 * Anteraja API - Laravel Library
 * Based on Anteraja Official Documentation (https://developer.anteraja.id/#anteraja-api-documentation-v2-0-7)
 */

class Anteraja
{
    public static function check_tariff($origin, $destination, $weight = 1)
    {
        $endpoint = env('ANTERAJA_BASE_PATH') . '/serviceRates';

        $access_key_id = env('ANTERAJA_ACCESS_KEY_ID');
        $secret_access_key = env('ANTERAJA_SECRET_ACCESS_KEY');

        if (!$access_key_id || !$secret_access_key) {
            if (env('APP_DEBUG')) {
                return 'Auth credentials for Anteraja is not set';
            } else {
                return false;
            }
        }

        /**
         * origin & destination used area code that generated by Anteraja
         * 
         * Parcel weight in gram(s). Minimum is 1,000. Maximum is 50,000.
         */

        // so need to convert weight from kg to gram
        $weight = $weight * 1000;
        // set minimum
        if ($weight < 1000) {
            $weight = 1000;
        }

        try {
            $client = new Client();
            $headers = [
                'access-key-id' => $access_key_id,
                'secret-access-key' => $secret_access_key,
                'Content-Type' => 'application/json',
            ];
            $result = $client->request('POST', $endpoint, [
                'headers' => $headers,
                'json' => [
                    'origin' => $origin,
                    'destination' => $destination,
                    'weight' => $weight
                ]
            ]);
            $response = json_decode($result->getBody()->getContents());

            return [
                'status' => true,
                'data' => $response->content->services
            ];

            // * Success Response Sample
            // array:2 [▼
            //     "status" => true
            //     "data" => array:3 [▼
            //         0 => {#761 ▼
            //             +"product_code": "REG"
            //             +"product_name": "Regular"
            //             +"etd": "1-2 Day"
            //             +"rates": 10000
            //         }
            //         1 => {#751 ▼
            //             +"product_code": "ND"
            //             +"product_name": "Next Day"
            //             +"etd": "1 Day"
            //             +"rates": 13000
            //         }
            //         2 => {#758 ▼
            //             +"product_code": "SD"
            //             +"product_name": "Same Day"
            //             +"etd": "0 Day"
            //             +"rates": 20000
            //         }
            //     ]
            // ]
        } catch (\GuzzleHttp\Exception\ClientException $e) {
            $response = $e->getResponse();
            $responseBodyAsString = json_decode($response->getBody()->getContents());
            # ERROR
            return [
                'status' => false,
                'info' => $responseBodyAsString->info
            ];

            // * Error Response Sample
            // array:2 [▼
            //     "status" => false
            //     "info" => "District not found : 31.72.55"
            // ]
        }

        # INTERNAL ERROR
        return [
            'status' => false,
            'info' => 'Internal Server Error in Anteraja Library'
        ];
    }

    public static function generate_awb($shipper, $customer, $product, $origin, $destination, $options)
    {
        
    }
}
